theme: plainwhite
baseurl: ""
plainwhite:
  name: Jamilla Akhund-Zade, Ph.D.
  tagline: Biology, Statistics, Data Science  
  date_format: "%b %-d, %Y"

  social_links:
    twitter: jamilla_az
    github: jamilla-az
    linkedIn: in/jamilla-akhund-zade/

  navigation:
    - title: My Work
      url: "https://orcid.org/0000-0001-5589-8258"
    - title: de Bivort Lab
      url: "http://debivort.org/"