remote_theme: thelehhman/plainwhite-jekyll
plainwhite:
  name: Jamilla Akhund-Zade
  tagline: personal page
  date_format: "%b %-d, %Y"

  social_links:
    twitter: https://twitter.com/jamilla_az
    github: https://github.com/jamilla-az
    linkedIn: https://www.linkedin.com/in/jamilla-akhund-zade/
    
  navigation:
    - title: My Work
      url: "/my-work"
    - title: Resume
      url: "/resume"