theme: plainwhite
baseurl: ""
plainwhite:
  name: Jamilla Akhund-Zade
  tagline: personal page
  date_format: "%b %-d, %Y"

  social_links:
    twitter: jamilla_az
    github: jamilla-az
    linkedIn: in/jamilla-akhund-zade/

  navigation:
    - title: My Work
      url: "/my-work"
    - title: Resume
      url: "/resume"